# Generated by Django 4.2.7 on 2024-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CreditApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="monthly_payment",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
