# Generated by Django 4.2.7 on 2024-01-17 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CreditApp", "0002_loan_monthly_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="current_debt",
        ),
    ]
