# Generated by Django 4.2.7 on 2024-01-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CreditApp", "0003_remove_customer_current_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="monthly_income",
            field=models.FloatField(null=True),
        ),
    ]
