# Generated by Django 4.2.7 on 2024-01-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CreditApp", "0004_alter_customer_monthly_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="monthly_payment",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="tenure",
            field=models.IntegerField(null=True),
        ),
    ]
