# Generated by Django 4.2.7 on 2024-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CreditApp", "0005_alter_loan_interest_rate_alter_loan_loan_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="emis_paid_on_time",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
