# Generated by Django 4.2.7 on 2024-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CreditApp", "0006_alter_loan_emis_paid_on_time_alter_loan_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="approved_limit",
            field=models.FloatField(null=True),
        ),
    ]
