version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=creditsystem
      - POSTGRES_USER=Ashwin
      - POSTGRES_PASSWORD=abcd1234
    healthcheck:
          test: ["CMD", "pg_isready", "-q"]
    ports:
      - "5432:5432"
  web:
    build: .
    command: ./docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=creditsystem
      - POSTGRES_USER=Ashwin
      - POSTGRES_PASSWORD=abcd1234
    depends_on:
      db:
        condition: service_healthy